ContratosBundle\Entity\Trabajo:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fecha:
            type: datetime
        ciudad:
            type: string
            length: 100
            nullable: true
        empleador_persona:
            type: string
            length: 20
            nullable: true
        empleador_natural_sexo:
            type: string
            length: 20
            options:
                default: Hombre
        empleador_natural_nombres:
            type: string
            length: 100
            nullable: true
        empleador_natural_apellido_paterno:
            type: string
            length: 100
            nullable: true
        empleador_natural_apellido_materno:
            type: string
            length: 100
            nullable: true
        empleador_natural_nacionalidad:
            type: string
            length: 100
            nullable: true
        empleador_natural_estado_civil:
            type: string
            length: 100
            nullable: true
        empleador_natural_profesion:
            type: string
            length: 100
            nullable: true
        empleador_natural_rut:
            type: string
            length: 100
            nullable: true
        empleador_natural_domicilio:
            type: string
            length: 100
            nullable: true
        empleador_natural_region:
            type: string
            length: 100
            nullable: true
        empleador_juridica_razon:
            type: string
            length: 100
            nullable: true
        empleador_juridica_giro:
            type: string
            length: 100
            nullable: true
        empleador_juridica_rut:
            type: string
            length: 100
            nullable: true
        empleador_juridica_domicilio:
            type: string
            length: 100
            nullable: true
        empleador_juridica_region:
            type: string
            length: 100
            nullable: true
        empleador_juridica_personeria_fecha:
            type: datetime
            nullable: true
        empleador_juridica_personeria_notaria:
            type: string
            length: 100
            nullable: true
        empleador_juridica_personeria_lugar:
            type: string
            length: 100
            nullable: true
        trabajador_sexo:
            type: string
            length: 20
            options:
                default: Hombre
        trabajador_nombres:
            type: string
            length: 100
            nullable: true
        trabajador_apellido_paterno:
            type: string
            length: 100
            nullable: true
        trabajador_apellido_materno:
            type: string
            length: 100
            nullable: true
        trabajador_extranjero:
            type: boolean
            options:
                default: 0
        trabajador_nacionalidad:
            type: string
            length: 100
            nullable: true
        trabajador_procedencia:
            type: string
            length: 100
            nullable: true
        trabajador_visa:
            type: string
            length: 100
            nullable: true
        trabajador_estado_civil:
            type: string
            length: 100
            nullable: true
        trabajador_profesion:
            type: string
            length: 100
            nullable: true
        trabajador_rut:
            type: string
            length: 100
            nullable: true
        trabajador_nacimiento:
            type: datetime
            nullable: true
        trabajador_domicilio:
            type: string
            length: 100
            nullable: true
        trabajador_region:
            type: string
            length: 100
            nullable: true
        actividad_empresa:
            type: string
            length: 255
            nullable: true        
        actividad_empleado_funciones:
            type: string
            length: 255
            nullable: true 
        actividad_empleado_responsabilidades:
            type: string
            length: 255
            nullable: true
        lugar_trabajo:
            type: string
            length: 100
            nullable: true
        lugar_direccion:
            type: string
            length: 255
            nullable: true
        lugar_ciudad:
            type: string
            length: 255
            nullable: true
        lugar_otro:
            type: string
            length: 255
            nullable: true
        duracion_jornada_tipo:
            type: string
            length: 100
            nullable: true
        duracion_jornada_cantidad_completa:
            type: integer
            length: 11
            nullable: true
        duracion_jornada_cantidad_parcial:
            type: integer
            length: 11
            nullable: true
        duracion_jornada_colacion:
            type: string
            length: 100
            nullable: true
        duracion_jornada_alternativa:
            type: boolean
            options:
                default: 0
        sueldo_monto:
            type: decimal
            scale: 2
            nullable: true
        sueldo_unidad:
            type: string
            length: 100
            nullable: true
        sueldo_frecuencia:
            type: string
            length: 100
            nullable: true
        sueldo_periodo:
            type: string
            length: 100
            nullable: true
        sueldo_afp:
            type: string
            length: 100
            nullable: true
        sueldo_salud:
            type: string
            length: 100
            nullable: true
        sueldo_otra_remuneracion:
            type: boolean
            options:
                default: 0
        sueldo_otra_remuneracion_comision:
            type: boolean
            options:
                default: 0
        sueldo_otra_remuneracion_comision_texto:
            type: string
            length: 255
            nullable: true
        sueldo_otra_remuneracion_participacion:
            type: boolean
            options:
                default: 0
        sueldo_otra_remuneracion_participacion_texto:
            type: string
            length: 255
            nullable: true
        sueldo_otra_remuneracion_otro:
            type: boolean
            options:
                default: 0
        sueldo_otra_remuneracion_otro_texto:
            type: string
            length: 255
            nullable: true
        sueldo_otra_beneficios:
            type: boolean
            options:
                default: 0
        sueldo_otra_beneficios_descripcion:
            type: string
            length: 500
            nullable: true
        duracion_contrato_tipo:
            type: string
            length: 100
            nullable: true
        duracion_contrato_cantidad:
            type: integer
            length: 11
            nullable: true
        duracion_contrato_unidad:
            type: string
            length: 100
            nullable: true
        duracion_contrato_obra:
            type: string
            length: 255
            nullable: true
        duracion_contrato_periodo:
            type: string
            length: 100
            nullable: true
        duracion_contrato_fecha:
            type: datetime
            nullable: true
        prestacion_fecha:
            type: datetime
            nullable: true
    manyToMany:
        trabajo_oficial_jornadas:
          targetEntity: Jornada
          cascade: ["persist", "merge"]
          joinTable:
            name: trabajo_oficial_jornada
            joinColumns:
              oficial_id:
                referencedColumnName: id
            inverseJoinColumns:
              jornada_id:
                referencedColumnName: id
                unique: true
        trabajo_alternativa_jornadas:
          targetEntity: Jornada
          cascade: ["persist", "merge"]
          joinTable:
            name: trabajo_alternativa_jornada
            joinColumns:
              alternativa_id:
                referencedColumnName: id
            inverseJoinColumns:
              jornada_id:
                referencedColumnName: id
                unique: true
        empleador_juridica_representantes:
          targetEntity: RepresentanteLegal
          cascade: ["persist", "merge"]
          joinTable:
            name: empleador_representante
            joinColumns:
              trabajo_id:
                referencedColumnName: id
            inverseJoinColumns:
              representante_id:
                referencedColumnName: id
                unique: true
    manyToOne:
        empleador_natural_comuna:
            targetEntity: Comuna
            joinColumn:
                name: comuna_empleador_natural_id
                referencedColumnName: id
        empleador_juridica_comuna:
            targetEntity: Comuna
            joinColumn:
                name: comuna_empleador_juridica_id
                referencedColumnName: id
        trabajador_comuna:
            targetEntity: Comuna
            joinColumn:
                name: comuna_trabajador_id
                referencedColumnName: id
        jurisdiccion_comuna:
            targetEntity: Comuna
            joinColumn:
                name: comuna_jurisdiccion_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
